# roles/system_config/tasks/main.yml

- name: Set hostname
  import_tasks: hostname.yml

- name: Update /etc/hosts
  import_tasks: hostsfile.yml

- name: Disable swap
  import_tasks: disable_swap.yml

- name: Load kernel modules for Kubernetes
  import_tasks: kernel_modules.yml

- name: Set sysctl values for Kubernetes networking
  import_tasks: sysctl.yml
  