# roles/system_config/tasks/sysctl.yml

- name: Persist Kubernetes-related sysctl settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl settings from /etc/sysctl.d
  ansible.builtin.command: sysctl --system
  changed_when: true
